#!/bin/bash
# vi: set sw=4 ts=4 ai:
#
# Author : Ton Kersten
# Date   : 2023-10-12

# Use `curl` to run a template on the AAP server.
# In the template, tick the "Provisioning Callbacks"
# box, generate a random key and put that in the
# "Host Config Key" field.

AAP_HOST="https://aap.ansilab.nl"
KEY="<your secret key>"
URL="${AAP_HOST}/api/v2/job_templates/13/callback/"

payload="$(jo -p							\
	host_config_key=${KEY}					\
	extra_vars="$(jo						\
		firstname=Ton						\
		lastname=Kersten					\
		holiday='Reykjavík'					\
		skills='Call AAPI\nRun Anisble'		\
	)"										\
)"

curl -k -f -i								\
	-H 'Content-Type:application/json'		\
	-XPOST									\
	--data "${payload}"						\
	${URL}

