#!/bin/bash
# vi: set sw=4 ts=4 ai:
#
# Author : Ton Kersten
# Date   : 2023-10-12

# Use `curl` to run a template on the AAP server.
# This template runs as if the "launch" key is pressed.

# Steps:
# - Find the template URL through https://..../api/v2/job_templates/<id>/launch/
#   (Do NOT forget the ending "/")
# - Create a new application with the launch URL as endpoint
# - Create a personal token to authenticate the run

# It's also possible to use the template name instead of the ID
# This is shown in the API in the "named_url" field.

AAP_HOST="https://aap.ansilab.nl"
TOKEN="<your secret token>"
URL="${AAP_HOST}/api/v2/job_templates/TMPL%20%7C%20Ping%20all%20hosts++Ansible%20Lab/launch/"
URL="${AAP_HOST}/api/v2/job_templates/11/launch/"

curl -k -s -X POST								\
	-H "Content-Type: application/json"			\
	-H "Authorization: Bearer ${TOKEN}"			\
	${URL}										| \
	jq '.'
