---
#
# Run:
#   ansible-builder build --tag git.ansilab.nl/tonk/ee_rocky:1.7
#   podman login git.ansilab.nl
#   podman push git.ansilab.nl/tonk/ee_rocky:1.7
#
# To test and check:
#   podman run -u root  -it --rm git.ansilab.nl/tonk/ee_rocky:1.7
#
# See: https://ansible.readthedocs.io/projects/builder/en/latest/definition/
# See: https://github.com/RHA-Automation/notes/blob/main/2023-06-28-building-complex-execution-environments.md
#
#
version: 3

options:
  package_manager_path: /usr/bin/dnf

images:
  base_image:
    #name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest
    # Other available base images:
    #   - docker.io/redhat/ubi9:latest
    #   - quay.io/rockylinux/rockylinux:9
    #   - quay.io/centos/centos:stream9
    #   - registry.fedoraproject.org/fedora:38
    #   - registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest
    #   - registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest
    name: quay.io/rockylinux/rockylinux:9

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.8

  ansible_runner:
    package_pip: ansible-runner

  python_interpreter:
    package_system: "python3.9"
    python_path: "/usr/bin/python3"

  #
  # requirements.yml
  #
  galaxy: |
    ---
    collections:
      - name: ansible.netcommon
      - name: ansible.posix
      - name: ansible.utils
      - name: ansible.windows
      - name: awx.awx
      - name: community.general
      - name: community.hashi_vault
      - name: community.libvirt
      - name: community.mysql
      - name: community.network
      - name: community.postgresql
      - name: redhatinsights.insights
      - name: checkmk.general

  #
  # bindeps.txt
  #
  system: |
    git [platform:rpm]
    openssl [platform:rpm]
    ca-certificates [platform:rpm]
    bind-utils [platform:rpm]
    python-dns [platform:rpm]

  #
  # requirements.txt
  #
  python: |
    hvac
    passlib

additional_build_files:
  - src: files/ansible.cfg
    dest: configs

additional_build_steps:
  append_base:
    - RUN /usr/bin/dnf -y upgrade
    - RUN $PYCMD -m pip install -U pip

  append_final:
    - RUN mkdir -p /etc/ansible
    - COPY _build/configs/ansible.cfg /runner/.ansible.cfg
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN update-ca-trust
    - RUN mkdir -p /var/run/receptor
    - RUN echo This is a post-install command!
    - RUN cat /etc/redhat-release
